---
title: "About"
---

```{r setup, include=FALSE}
# Change index.html above to about.html, once site is setup
# For now, I'm following the instructions at:
# https://resources.github.com/whitepapers/github-and-rstudio/
# In these instructions, the first part of file.path was 'dirname(input_file)' assuming the file
# was in the main directory. However, I'm following my practice of putting .Rmd files in the 
# rmarkdown directory. To get knitr to work, I've used the rprojroot command to redirect to main
# directory.  
# These elements were used initially to build the first html file:
# knit: (function(input_file, encoding) {
#   out_dir <- 'html';
#   rmarkdown::render(input_file,
#  encoding=encoding,
#  output_file=file.path(rprojroot::find_rstudio_root_file(), out_dir, 'index.html'))})
# output: html_document
knitr::opts_chunk$set(echo = TRUE)
# knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

Name: E Bryan Crenshaw III, PhD

The name, *52 Weekly Saunter Challenge*, is derived from a quote ascribed to [John Muir](https://www.etymonline.com/columns/post/john-muir-and-%27saunter%27):

>
     Hiking - "I don't like either the word or the thing. People ought to saunter in the mountains - not hike! Do you know the origin of that word 'saunter?' It's a beautiful word. Away back in the Middle Ages people used to go on pilgrimages to the Holy Land, and when people in the villages through which they passed asked where they were going, they would reply, 'A la sainte terre,' 'To the Holy Land.' And so they became known as sainte-terre-ers or saunterers. Now these mountains are our Holy Land, and we ought to saunter through them reverently, not 'hike' through them." 
- John Muir 
>

*Outdoors Certifications:* Certified as a Sierra Club Outings Leader with a primary focus on getting veterans into nature at Camp Elk Tannery in rural Pennsylvania. To see photos of these outings, check out the [Vet Camping folder](https://photos.bcrenshaw.com/Events/Vet-Camping) on my [photography site](https://photos.bcrenshaw.com/). As a part of the qualification for Outings Leader, I also have a [Red Cross certification in first aid](https://www.redcross.org/take-a-class).

*Hike Tracking Software:* [Alltrails](https://www.alltrails.com/members/ebcrenshaw3) and/or [FitBit](https://www.fitbit.com/us/home) are used to track hikes, but only Alltrails tracks are publically available. 
